events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen <SERVER_IP>:8000;
        server_name _;
        root /datasets;
        client_header_timeout 300s;

        location / {
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;

            # 1. Zero-Copy Kernel
            sendfile on;

            # Nâng chunk lên 8MB hoặc 16MB để đẩy lượng dữ liệu lớn hơn mỗi system call
            sendfile_max_chunk 8m;

            # 2. Tối ưu gom và đẩy gói tin
            tcp_nopush on;
            tcp_nodelay on;

            # 3. Timeout truyền body và giữ kết nối
            keepalive_timeout 300s;
            send_timeout 300s;

            # 4. Tắt hoàn toàn giới hạn tốc độ và tối ưu socket buffer
            limit_rate 0;
            output_buffers 2 2m;
            
            # 5. Hỗ trợ Resume / Tải đa luồng qua Range requests
            max_ranges 512;
        }
    }
}